name: Rankup
author: FVZA, CyberTiger
version: ${version}

description: Allows players to pay for new ranks.

main: org.cyberiantiger.minecraft.rankup.Main
depend: [Vault]

commands:
    rankup:
        description: Pay to rank up to the next rank. 
permissions:
    rankup.*: 
        description: Give access to all rank up commands. 
        children:
            rankup.rankup: true
            rankup.version: true
            rankup.reload: true
            rankup.sign: true
    rankup.rankup:
        description: Permission to run the /rankup command. 
        default: true
    rankup.reload:
        description: Permission to run the /rankup reload command. 
        default: op
    rankup.version:
        description: Permission to run the /rankup version command. 
        default: op
    rankup.sign:
        description: Permission to create Rankup signs.
        default: op        