# Remember, YAML does not understand the 'tab' key. You must use spaces instead. 
# Note that this plugin REQUIRES you have Vault. Download it here: http://dev.bukkit.org/server-mods/vault/

# If this is true, it will override any groups when someone ranks up. Only worry about this if a given person may have multiple ranks. 
settings:
    override-groups: false
    do-not-edit-this: 1
# Groups are ordered in the succession you want them to be. Format as follows: rankname: price ( Price can have a decimal place ) 
ranks:
    guest: 0
    member: 15000